SENSOR_READ_DELAY_SEC = 60
WIFI_SSID = "<SSID>"
WIFI_PASS = "<PASS>"
MAX_CONN_TIME = 10
MQTT_SERVER = "<SERVER_IP>"
MQTT_USER = "<MQTT_USER>"
MQTT_PASS = "<MQTT_PASS>"
MQTT_TOPIC_PREFIX = "thermostat"
